# Generated by Django 5.1.3 on 2024-12-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finest', '0002_submittedwebsite_favored_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedwebsite',
            name='favored_by',
        ),
        migrations.AddField(
            model_name='submittedwebsite',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
