# Generated by Django 5.1.3 on 2025-01-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finest', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finest.submittedwebsite')),
            ],
        ),
    ]
