# Generated by Django 5.1.5 on 2025-01-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finest', '0007_siteoftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedwebsite',
            name='date_site_of_the_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
