# Generated by Django 5.1.5 on 2025-01-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finest', '0008_submittedwebsite_date_site_of_the_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteOfTheDay',
        ),
    ]
