# Generated by Django 5.1.5 on 2025-01-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finest', '0009_delete_siteoftheday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
