# Generated by Django 5.1.5 on 2025-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finest', '0011_profile_github_profile_instagram_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
