# Generated by Django 5.1.5 on 2025-02-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finest', '0014_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='finest.follow'),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
    ]
